# Generated by Django 3.0 on 2021-04-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('decripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField()),
                ('precio', models.TextField()),
                ('descripcion', models.TextField()),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Categoria')),
            ],
        ),
    ]
