# Generated by Django 3.0 on 2021-04-21 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vehiculos.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehiculos', '0002_auto_20210421_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(default=1, upload_to=vehiculos.models.url_vehiculo),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cuidad', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=100)),
                ('gerente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculos', models.ManyToManyField(to='vehiculos.Vehiculo')),
            ],
        ),
    ]
